# Generated by Django 3.2.13 on 2022-10-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_alter_inquiry_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Allocated', 'Allocated')], default=('Client', 'Client'), max_length=9),
        ),
    ]
