# Generated by Django 3.2.13 on 2022-10-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0003_inquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Allocated', 'Allocated')], default=('Pending', 'Pending'), max_length=9),
        ),
    ]
