# Generated by Django 3.2 on 2022-06-29 15:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_number',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('landline_number', models.CharField(max_length=11)),
                ('mobile_number', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_of_notes', models.CharField(choices=[('TBA', 'to be allocated'), ('INT', 'interviewing'), ('NCP', 'cleaner accepted'), ('DC', 'dead/inactive client')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='zipCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('zip_code', models.CharField(blank=True, default='0', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('address_line_2', models.CharField(max_length=30)),
                ('address_line_3', models.CharField(max_length=30)),
                ('address_line_1', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('date_added', models.DateTimeField()),
                ('preferred_day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesdat'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=8)),
                ('type', models.CharField(choices=[('RE', 'Regular'), ('O-F', 'One Off')], max_length=6)),
                ('frequency', models.CharField(choices=[('1', 'Weekly'), ('2', 'Monthly'), ('3', 'Fortnightly')], max_length=10)),
                ('number_of_hours', models.IntegerField()),
                ('paying', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=3)),
                ('paying_methods', models.CharField(choices=[('1', 'DD'), ('2', 'Standing Order(SO)'), ('3', 'Card')], max_length=13)),
                ('payment_reference', models.CharField(max_length=40)),
                ('email_to_client', models.EmailField(max_length=254)),
                ('contact_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.contact_number')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.status')),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.zipcode')),
            ],
        ),
    ]
