# Generated by Django 3.2.13 on 2022-09-19 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0007_cleaners_notes'),
        ('clients', '0003_clients_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='cleaner_allocated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cleaners.cleaners'),
        ),
    ]
