# Generated by Django 3.2.13 on 2022-07-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_clients_email_to_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='preferred_day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=8),
        ),
    ]
