# Generated by Django 3.2.13 on 2022-09-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_clients_cleaner_allocated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
