# Generated by Django 3.2.13 on 2022-11-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20221104_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailssenttoclient',
            name='email_subject',
            field=models.CharField(max_length=50),
        ),
    ]
