# Generated by Django 3.2 on 2022-07-20 07:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_clients_preferred_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_templates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('template_name', models.CharField(max_length=50)),
            ],
        ),
    ]
