# Generated by Django 3.2.13 on 2022-09-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_clients_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='date_added',
            field=models.DateField(),
        ),
    ]
