# Generated by Django 3.2.13 on 2022-10-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaners',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='cleaners',
            name='notes',
            field=models.TextField(default='15.10.2022 12:41:02'),
        ),
    ]
