# Generated by Django 3.2.13 on 2022-07-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0002_auto_20220702_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaners',
            name='tel_number',
        ),
        migrations.AddField(
            model_name='cleaners',
            name='landline_number',
            field=models.CharField(default='0', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cleaners',
            name='mobile_number',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
