# Generated by Django 3.2.13 on 2022-09-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0002_auto_20220826_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleaners',
            old_name='NI_Nunber',
            new_name='NI_Number',
        ),
        migrations.AddField(
            model_name='cleaners',
            name='permit_image',
            field=models.ImageField(blank=True, null=True, upload_to='permit_images/'),
        ),
        migrations.AlterField(
            model_name='cleaners',
            name='referee_1_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cleaners',
            name='referee_2_details',
            field=models.TextField(),
        ),
    ]
