# Generated by Django 3.2.13 on 2022-10-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0002_auto_20221015_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaners',
            name='notes',
            field=models.TextField(default='15.10.2022 12:42:10'),
        ),
    ]
