# Generated by Django 3.2.13 on 2022-09-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0003_auto_20220912_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaners',
            name='type_of_allergy',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
