# Generated by Django 3.2.13 on 2022-07-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0003_auto_20220702_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaners',
            name='has_car',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='cleaners',
            name='prev_work_experience',
            field=models.CharField(max_length=30),
        ),
    ]
