# Generated by Django 3.2.13 on 2022-09-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0004_alter_cleaners_type_of_allergy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleaners',
            old_name='Disclouser',
            new_name='Disclosure',
        ),
    ]
