# Generated by Django 3.2.13 on 2022-07-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0006_rename_post_code_cleaners_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaners',
            name='valid_cleaner',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'No')], max_length=3),
        ),
    ]
