# Generated by Django 3.2.13 on 2022-08-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0007_cleaners_valid_cleaner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaners',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
