# Generated by Django 3.2.13 on 2022-08-09 15:52

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0008_cleaners_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='sent_emails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email_subject', models.CharField(max_length=50)),
                ('email_body', ckeditor.fields.RichTextField(blank=True, default='None')),
            ],
        ),
    ]
